export const lumina = {
  title: "lumina",
  link: "lumina",
  image: "/buildings/lumina/lumina.jpg",
  logo: "/buildings/lumina/logo.png",
  address: "Av. Leopoldo Zarling, 1890, Bombas, Bombinhas – SC",
  deadline: "2025-10-01T03:00:00.000Z",
  apartments: [
    {
      ID: "1",
      tower: "A",
      floor: "3",
      apartmentNumber: "301A",
      availability: "sold",
      area: "125.04",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "2",
      tower: "A",
      floor: "3",
      apartmentNumber: "302A",
      availability: "sold",
      id: "2",
      area: "151.14",
      suites: "4",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "3",
      tower: "A",
      floor: "3",
      apartmentNumber: "303A",
      availability: "sold",
      area: "126.43",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "4",
      tower: "A",
      floor: "3",
      apartmentID: "4",
      availability: "sold",
      area: "127.45",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "5",
      tower: "A",
      floor: "3",
      apartmentNumber: "305A",
      availability: "sold",
      area: "127.56",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "6",
      tower: "A",
      floor: "3",
      apartmentNumber: "306A",
      availability: "sold",
      area: "108.56",
      suites: "1",
      demiSuites: "2",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "7",
      tower: "A",
      floor: "3",
      apartmentNumber: "307A",
      availability: "sold",
      area: "106.29",
      suites: "1",
      demiSuites: "2",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "8",
      tower: "A",
      floor: "3",
      apartmentID: "8",
      apartmentNumber: "308A",
      availability: "sold",
      area: "125.1",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "9",
      tower: "A",
      floor: "4",
      apartmentNumber: "401A",
      availability: "sold",
      area: "125.04",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "10",
      tower: "A",
      floor: "4",
      apartmentNumber: "402A",
      availability: "sold",
      area: "151.14",
      suites: "4",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "11",
      tower: "A",
      floor: "4",
      apartmentNumber: "403A",
      availability: "sold",
      area: "126.43",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "12",

      tower: "A",
      floor: "4",
      apartmentNumber: "404A",
      availability: "sold",
      area: "127.45",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "13",
      tower: "A",
      floor: "4",
      apartmentNumber: "405A",
      availability: "sold",
      area: "127.56",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "14",
      tower: "A",
      floor: "4",
      apartmentNumber: "406A",
      availability: "sold",
      area: "108.56",
      suites: "1",
      demiSuites: "2",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "15",
      tower: "A",
      floor: "4",
      apartmentNumber: "407A",
      availability: "sold",
      area: "106.29",
      suites: "1",
      demiSuites: "2",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "16",
      tower: "A",
      floor: "4",
      apartmentNumber: "408A",
      availability: "sold",
      area: "125.1",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "17",

      tower: "A",
      floor: "5",
      apartmentNumber: "501A",
      availability: "sold",
      area: "125.04",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "18",
      tower: "A",
      floor: "5",
      apartmentNumber: "502A",
      availability: "sold",
      area: "151.14",
      suites: "4",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "19",
      tower: "A",
      floor: "5",
      apartmentNumber: "503A",
      availability: "sold",
      area: "126.43",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "20",
      tower: "A",
      floor: "5",
      apartmentNumber: "504A",
      availability: "sold",
      area: "127.45",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "21",
      tower: "A",
      floor: "5",
      apartmentNumber: "505A",
      availability: "sold",
      area: "127.56",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "22",
      tower: "A",
      floor: "5",
      apartmentNumber: "506A",
      availability: "sold",
      area: "108.56",
      suites: "1",
      demiSuites: "2",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "23",

      tower: "A",
      floor: "5",
      apartmentNumber: "507A",
      availability: "sold",
      area: "106.29",
      suites: "1",
      demiSuites: "2",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "24",
      tower: "A",
      floor: "5",
      apartmentNumber: "508A",
      availability: "sold",
      area: "125.1",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "25",
      tower: "A",
      floor: "6",
      apartmentNumber: "601A",
      availability: "negotiation",
      area: "125.04",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "26",
      tower: "A",
      floor: "6",
      apartmentNumber: "602A",
      availability: "available",
      area: "151.14",
      suites: "4",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "27",
      tower: "A",
      floor: "6",
      apartmentNumber: "603A",
      availability: "sold",
      area: "126.43",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "28",
      tower: "A",
      floor: "6",
      apartmentNumber: "604A",
      availability: "sold",
      area: "127.45",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "29",
      tower: "A",
      floor: "6",
      apartmentNumber: "605A",
      availability: "available",
      area: "127.56",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "30",
      tower: "A",
      floor: "6",
      apartmentNumber: "606A",
      availability: "sold",
      area: "108.56",
      suites: "1",
      demiSuites: "2",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "31",
      tower: "A",
      floor: "6",
      apartmentNumber: "607A",
      availability: "available",
      area: "106.29",
      suites: "1",
      demiSuites: "2",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
    {
      ID: "32",
      tower: "A",
      floor: "6",
      apartmentNumber: "608A",
      availability: "negotiation",
      area: "125.1",
      suites: "3",
      demiSuites: "0",
      blueprintURL:
        "https://tabelas.gkempreendimentos.com.br/wp-content/uploads/2022/12/01B-768x1024.png",
    },
  ],
};
